repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
    id: google-java-formatter
    name: "Google Java Formatter"
    rev: a6273196190bb0f68caf1dc68073cf62c719f725  # frozen: v2.14.0
    hooks:
      - id: pretty-format-java
        args: [--autofix, --google-java-formatter-version=1.35.0]
